# Generated by Django 3.2.7 on 2023-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122, unique=True)),
                ('mobile', models.CharField(max_length=122, unique=True)),
                ('gender', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=122)),
                ('qualification', models.CharField(max_length=122)),
                ('batch', models.CharField(max_length=122)),
                ('college', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
            ],
        ),
    ]
