# Generated by Django 3.2.7 on 2023-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engross_app', '0002_auto_20231125_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformdata',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
